[[redirects]]
  from = "/vocab/*"
  to = "https://rightsstatements.graphthinking.com/vocab/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}

[[redirects]]
  from = "/data/*"
  to = "https://rightsstatements.graphthinking.com/data/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}

[[redirects]]
  from = "/page/*"
  to = "https://rightsstatements.graphthinking.com/page/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}
