[[redirects]]
  from = "/vocab/*"
  to = "https://rightsstatements.graphthinking.com/"
  status = 200
  headers = {X-Forwarded-Host = "${X_FORWARDED_HOST}", X-Forwarded-Protocol = "${X_FORWARDED_PROTO}"}

[[redirects]]
  from = "/data/*"
  to = "https://rightsstatements.graphthinking.com/"
  status = 200
  headers = {X-Forwarded-Host = "${X_FORWARDED_HOST}", X-Forwarded-Protocol = "${X_FORWARDED_PROTO}"}

[[redirects]]
  from = "/page/*"
  to = "https://rightsstatements.graphthinking.com/"
  status = 200
  headers = {X-Forwarded-Host = "${X_FORWARDED_HOST}", X-Forwarded-Protocol = "${X_FORWARDED_PROTO}"}
