[build]
  publish = "_site"
  command = "node scripts/writeConf.js && jekyll build"

[context.production]
  command = "node scripts/writeConf.js && jekyll build --config _config_production.yml"

[[redirects]]
  from = "/vocab/*"
  to = "http://rights-prod.rightsstatements.org/vocab/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}

[[redirects]]
  from = "/data/*"
  to = "http://rights-prod.rightsstatements.org/data/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}

[[redirects]]
  from = "/page/*"
  to = "http://rights-prod.rightsstatements.org/page/:splat"
  status = 200
  headers = {X-Deploy-Url = "${X_DEPLOY_URL}"}
